version: "3.8"

services:
  redis:
    image: redis
  database:
    image: postgres
    restart: always
    environment: 
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports: 
      - 5432:5432
    #volumes:
    #  - "./scripts/database/init.sql:/init.sql/"

  project:
    container_name: whatsapp-api
    build:
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - '.:app'
      - '/app/node_modules'
    
    ports:
      - '4000:4000'

    environment:
      TZ: "UTC"
      PORT: 4000
      NODE_ENV: "local"
      BASE_APP: "./src"

      #Database
      DATABASE_URL: "postgresql://postgres:root@localhost:root/whatsapp?schema=public"

      #SecretKey
      PRIVATE_KEY: "Uvyno8HNbhvOp8qAHxbH0G8zZe4J26N6PHs6hZ1h"
    
    depends_on: 
      - database
